# TODO: remove this file by either moving cops here or fixing code
inherit_from:
  - .rubocop_todo.yml

AllCops:
  Include:
    - 'Rakefile'
    - 'app/views/foreman_tasks/api/**/*.rabl'
    - lib/**/*.rake

Lint/ShadowingOuterLocalVariable:
  Enabled: false

Rails:
  Enabled: true

# Don't prefer is_a? over kind_of?
Style/ClassCheck:
  Enabled: false

# Don't enforce documentation
Style/Documentation:
  Enabled: false

# Support both ruby19 and hash_rockets
Style/HashSyntax:
  Enabled: false

# Both double and single quotes are OK
Style/StringLiterals:
  Enabled: false

# Don't enforce frozen string literals
Style/FrozenStringLiteralComment:
  Enabled: false
